#pragma once

#include "nengo/base.hpp"
#include <Eigen/Dense>
#include <functional>

namespace nengo {

/**
 * Provide non-neural inputs to Nengo objects and process outputs.
 * 
 * Equivalent to nengo.node.Node in Python version.
 * 
 * Nodes can accept input, and perform arbitrary computations
 * for the purpose of controlling a Nengo simulation.
 * Nodes are typically not part of a brain model per se,
 * but serve to summarize the assumptions being made
 * about sensory data or other environment variables
 * that cannot be generated by a brain model alone.
 * 
 * Parameters
 * ----------
 * output : callable, VectorXd, or nullptr, optional
 *     Function that transforms the Node inputs into outputs,
 *     a constant output value, or nullptr to transmit signals unchanged
 *     (default: nullptr for passthrough).
 * size_in : int, optional
 *     The number of dimensions of the input data parameter (default: 0).
 * size_out : int, optional
 *     The size of the output signal. If not specified, it will be determined
 *     based on the values of ``output`` and ``size_in`` (default: auto-determined).
 * label : string, optional
 *     A descriptive label for the object (default: "").
 * seed : int, optional
 *     Random number seed. Note: no aspects of the node are random,
 *     so currently setting this seed has no effect (default: None).
 * 
 * Attributes
 * ----------
 * size_in : int
 *     The number of dimensions for incoming connection.
 * size_out : int
 *     The number of dimensions for outgoing connection.
 */
class Node : public NengoObject {
public:
    using OutputFunction = std::function<Eigen::VectorXd(double, const Eigen::VectorXd&)>;

    /**
     * Constructor for Node matching Python signature.
     * @param output Function that computes output or constant output vector
     * @param size_in Number of input dimensions (default: 0)
     * @param size_out Number of output dimensions (default: None, determined automatically)
     * @param label Label for the node
     * @param seed Random number seed (currently unused like in Python)
     */
    explicit Node(OutputFunction output = nullptr,
                  int size_in = 0,
                  std::optional<int> size_out = std::nullopt,
                  const std::string& label = "",
                  std::optional<int> seed = std::nullopt);

    /**
     * Constructor for constant output Node.
     */
    explicit Node(const Eigen::VectorXd& output,
                  int size_in = 0,
                  const std::string& label = "",
                  std::optional<int> seed = std::nullopt);

    /**
     * Constructor for passthrough Node (identity function).
     */
    explicit Node(int size_in, 
                  const std::string& label = "",
                  std::optional<int> seed = std::nullopt);

    ~Node() override = default;

    // Getters matching Python properties
    int getSizeIn() const { return size_in_; }
    int getSizeOut() const { return size_out_; }
    bool hasOutput() const { return output_function_ != nullptr; }

    // Compute output
    Eigen::VectorXd run(double t, const Eigen::VectorXd& input = Eigen::VectorXd()) const;

    // String representation
    std::string toString() const override;

private:
    OutputFunction output_function_;
    int size_in_;
    int size_out_;
    Eigen::VectorXd constant_output_;
    bool is_constant_;
    bool is_passthrough_;

    void initializeAsPassthrough();
    void initializeAsConstant(const Eigen::VectorXd& output);
    void determineSizeOut(std::optional<int> size_out_param);
};

} // namespace nengo